### PR TITLE
chore: make kafka_init.sh executable

### PR DESCRIPTION
**Pull request by mcook42**
Track kafka_init.sh as executable so the file is executable in the resulting image. Without it, I was running into the following logs running the jpo-ode locally. This prevented the topic creation and caused many weird errors when running the stack locally

```txt
2024-12-11 14:20:21 /bin/sh: ./kafka_init.sh: Permission denied
2024-12-11 14:20:23 /bin/sh: ./kafka_init.sh: Permission denied
2024-12-11 14:20:24 /bin/sh: ./kafka_init.sh: Permission denied
2024-12-11 14:20:25 /bin/sh: ./kafka_init.sh: Permission denied
```

kafka_connector_init.sh and setup_mongo.sh were updated to be executable, too, to preemptively address similar permission issues with these two scripts

### CODE REVIEW

**Comment by Michael7371** [comment]
@mcook42 Should we also manually set the file permissions in the `Dockerfile.jikkou` as well? Also, can you apply the same update to the `kafka_connector_init.sh`.
For some reason on my computer I don't run into this error, are you running linux/macos?

**Comment by mcook42** [comment]
> @mcook42 Should we also manually set the file permissions in the `Dockerfile.jikkou` as well? Also, can you apply the same update to the `kafka_connector_init.sh`. For some reason on my computer I don't run into this error, are you running linux/macos?

Yeah, I'm running on linux. What do you mean by "manually set the file permissions in the Dockerfile.jikkou"? If you're wondering if we should make changes to `Dockerfile.jikkou`, then the answer would be no. The file permissions are copied over from the host machine during the image build, so if it's executable locally then it's executable in the image.

As for making `kafka_connector_init.sh` executable, that may be a good idea. I'll go ahead and make that update

**Comment by Michael7371** [comment]
> > @mcook42 Should we also manually set the file permissions in the `Dockerfile.jikkou` as well? Also, can you apply the same update to the `kafka_connector_init.sh`. For some reason on my computer I don't run into this error, are you running linux/macos?
> 
> Yeah, I'm running on linux. What do you mean by "manually set the file permissions in the Dockerfile.jikkou"? If you're wondering if we should make changes to `Dockerfile.jikkou`, then the answer would be no. The file permissions are copied over from the host machine during the image build, so if it's executable locally then it's executable in the image.
> 
> As for making `kafka_connector_init.sh` executable, that may be a good idea. I'll go ahead and make that update

Yeah, I think that makes sense. Thanks for updating the setup_mongo.sh script as well!

**Review by Michael7371 — APPROVED** [review]
Looks good!

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me!

**Pull request merged**
