### PR TITLE
Kafka Connect Module

### PR DESCRIPTION
**Pull request by Michael7371**
This PR includes code that was in jpo-s3-depositor. We are moving it here for the ODE and other repos to use.

### CODE REVIEW

**Comment by John-Wiens** [comment]
It looks like this PR has a folder for Kafka-Connect-Mongo which contains assets for Kafka Connect and Mongo. I was thinking that we would keep these components a bit more isolated. So the folder structure would look more like this:
KafkaConnect
    - Dockerfile
    - docker-compose.yml
    - scripts
        - connect-start.sh
Mongo
    - Dockerfile
    - docker-compose.yml
    - scripts
        - init-mongoDB.js

Then at the root of the project we can have a docker-compose file which has feature flags to turn different components on or off.

**Comment by Michael7371** [comment]
@John-Wiens this PR is now refactored based off of your comments

**Comment by John-Wiens** [comment]
I like it. Do we want to put a bunch of README.md files in all the sub directories just to finish mocking out the template?

**Comment by Michael7371** [comment]
> I like it. Do we want to put a bunch of README.md files in all the sub directories just to finish mocking out the template?

I'd prefer to keep it in the base README to reduce duplicating documentation. Or we could remove all the component specific items and have that in the sub folders. It's just alot of the logic comes down to the `.env` with the `COMPOSE_PROFILES` value and all that is at the root.

**Review by John-Wiens — APPROVED** [review]

**Review by John-Wiens — APPROVED** [review]

**Pull request merged**
